# Generated by Django 5.1.7 on 2025-03-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogauthor_options_alter_blogauthor_bio_and_more'),
    ]

    operations = [
    ]
